const coursesData = [
  {
    id: "1",
    name: "React for Beginners",
    description: "Learn the fundamentals of React.js and build interactive UIs from scratch.",
    duration: "6 weeks",
    price: 4999,
    discount_percent: 20,
    instructor: "John Smith",
    rating: 4.7,
    level: "Beginner",
    category: "Frontend",
    image: "/images/react-course.jpg",
  },
  {
    id: "2",
    name: "Mastering Node.js",
    description: "Understand server-side development with Node.js and Express framework.",
    duration: "8 weeks",
    price: 5999,
    discount_percent: 25,
    instructor: "Sarah Johnson",
    rating: 4.8,
    level: "Intermediate",
    category: "Backend",
    image: "/images/node-course.jpg",
  },
  {
    id: "3",
    name: "JavaScript Essentials",
    description: "Master core JavaScript concepts, from variables to advanced functions and DOM.",
    duration: "5 weeks",
    price: 3999,
    discount_percent: 10,
    instructor: "Michael Brown",
    rating: 4.6,
    level: "Beginner",
    category: "Programming",
    image: "/images/js-course.jpg",
  },
  {
    id: "4",
    name: "Advanced React Patterns",
    description: "Explore context API, custom hooks, and performance optimization in React.",
    duration: "7 weeks",
    price: 6999,
    discount_percent: 15,
    instructor: "Emily Davis",
    rating: 4.9,
    level: "Advanced",
    category: "Frontend",
    image: "/images/advanced-react.jpg",
  },
  {
    id: "5",
    name: "Python for Data Science",
    description: "Use Python libraries like NumPy, Pandas, and Matplotlib for data analysis.",
    duration: "8 weeks",
    price: 5499,
    discount_percent: 20,
    instructor: "Daniel Wilson",
    rating: 4.8,
    level: "Intermediate",
    category: "Data Science",
    image: "/images/python-data.jpg",
  },
  {
    id: "6",
    name: "Machine Learning with TensorFlow",
    description: "Build and train ML models using TensorFlow and Scikit-learn.",
    duration: "10 weeks",
    price: 7999,
    discount_percent: 30,
    instructor: "Olivia Garcia",
    rating: 4.9,
    level: "Advanced",
    category: "AI & ML",
    image: "/images/ml-course.jpg",
  },
  {
    id: "7",
    name: "Full-Stack Web Development Bootcamp",
    description: "Become a full-stack developer using React, Node.js, and PostgreSQL.",
    duration: "12 weeks",
    price: 9999,
    discount_percent: 35,
    instructor: "Chris Evans",
    rating: 4.9,
    level: "Intermediate",
    category: "Full Stack",
    image: "/images/fullstack.jpg",
  },
  {
    id: "8",
    name: "HTML & CSS Mastery",
    description: "Design responsive websites using HTML5, CSS3, and Flexbox/Grid.",
    duration: "4 weeks",
    price: 2999,
    discount_percent: 10,
    instructor: "Sophia Lee",
    rating: 4.5,
    level: "Beginner",
    category: "Frontend",
    image: "/images/html-css.jpg",
  },
  {
    id: "9",
    name: "UI/UX Design Fundamentals",
    description: "Learn design thinking, wireframing, and prototyping with Figma.",
    duration: "6 weeks",
    price: 4499,
    discount_percent: 15,
    instructor: "Liam Martinez",
    rating: 4.7,
    level: "Beginner",
    category: "Design",
    image: "/images/uiux.jpg",
  },
  {
    id: "10",
    name: "Django Web Development",
    description: "Develop robust web applications using Python’s Django framework.",
    duration: "8 weeks",
    price: 6499,
    discount_percent: 20,
    instructor: "Ava Taylor",
    rating: 4.8,
    level: "Intermediate",
    category: "Backend",
    image: "/images/django.jpg",
  },
  {
    id: "11",
    name: "C++ Programming Essentials",
    description: "Understand C++ syntax, OOP principles, and algorithms for beginners.",
    duration: "5 weeks",
    price: 3999,
    discount_percent: 15,
    instructor: "Noah Anderson",
    rating: 4.6,
    level: "Beginner",
    category: "Programming",
    image: "/images/cpp.jpg",
  },
  {
    id: "12",
    name: "Data Structures & Algorithms in Java",
    description: "Learn DSA with Java using practical examples and coding challenges.",
    duration: "7 weeks",
    price: 5999,
    discount_percent: 20,
    instructor: "Emma Thomas",
    rating: 4.8,
    level: "Intermediate",
    category: "Programming",
    image: "/images/java-dsa.jpg",
  },
  {
    id: "13",
    name: "AWS Cloud Practitioner",
    description: "Get started with AWS services, deployment, and cloud concepts.",
    duration: "6 weeks",
    price: 7499,
    discount_percent: 25,
    instructor: "Ethan White",
    rating: 4.7,
    level: "Beginner",
    category: "Cloud",
    image: "/images/aws.jpg",
  },
  {
    id: "14",
    name: "Cybersecurity Fundamentals",
    description: "Understand network security, encryption, and ethical hacking basics.",
    duration: "8 weeks",
    price: 6999,
    discount_percent: 20,
    instructor: "Mia Harris",
    rating: 4.8,
    level: "Intermediate",
    category: "Security",
    image: "/images/cyber.jpg",
  },
  {
    id: "15",
    name: "Blockchain Development",
    description: "Build decentralized apps (DApps) using Ethereum and Solidity.",
    duration: "10 weeks",
    price: 8999,
    discount_percent: 30,
    instructor: "James Clark",
    rating: 4.9,
    level: "Advanced",
    category: "Blockchain",
    image: "/images/blockchain.jpg",
  },
  {
    id: "16",
    name: "Kotlin for Android Development",
    description: "Learn to build Android apps using Kotlin and Android Studio.",
    duration: "9 weeks",
    price: 6499,
    discount_percent: 25,
    instructor: "Ella Rodriguez",
    rating: 4.7,
    level: "Intermediate",
    category: "Mobile",
    image: "/images/kotlin.jpg",
  },
  {
    id: "17",
    name: "Flutter App Development",
    description: "Create cross-platform mobile apps using Flutter and Dart.",
    duration: "8 weeks",
    price: 6999,
    discount_percent: 20,
    instructor: "Benjamin Lewis",
    rating: 4.8,
    level: "Intermediate",
    category: "Mobile",
    image: "/images/flutter.jpg",
  },
  {
    id: "18",
    name: "SQL & Database Management",
    description: "Master SQL queries, database design, and PostgreSQL operations.",
    duration: "6 weeks",
    price: 4999,
    discount_percent: 15,
    instructor: "Charlotte Walker",
    rating: 4.6,
    level: "Beginner",
    category: "Database",
    image: "/images/sql.jpg",
  },
  {
    id: "19",
    name: "DevOps with Docker & Kubernetes",
    description: "Learn CI/CD pipelines and container orchestration for modern deployments.",
    duration: "9 weeks",
    price: 8499,
    discount_percent: 30,
    instructor: "Alexander Scott",
    rating: 4.9,
    level: "Advanced",
    category: "DevOps",
    image: "/images/devops.jpg",
  },
  {
    id: "20",
    name: "Artificial Intelligence Basics",
    description: "Understand AI fundamentals, neural networks, and real-world use cases.",
    duration: "8 weeks",
    price: 7499,
    discount_percent: 25,
    instructor: "Grace King",
    rating: 4.8,
    level: "Beginner",
    category: "AI & ML",
    image: "/images/ai.jpg",
  },
];

export default coursesData;
